workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    # Uncomment below after setting up App Store Connect integration in Codemagic dashboard
    # integrations:
    #   app_store_connect: codemagic
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.talkswithluna.appname
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 22
      xcode: latest
      cocoapods: default
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      
      - name: Build web app
        script: |
          npm run build
      
      - name: Add iOS platform if needed
        script: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi
          npx cap sync ios
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          ls -la
          pod install --repo-update
      
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    
    # Uncomment after setting up App Store Connect integration
    # publishing:
    #   app_store_connect:
    #     auth: integration
    #     submit_to_testflight: true
    #     # submit_to_app_store: true
