workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    integrations:
      app_store_connect: codemagic
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.talkswithluna.appname
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
      node: 22
      xcode: latest
      cocoapods: default
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      
      - name: Build web app
        script: |
          npm run build
      
      - name: Add iOS platform and sync
        script: |
          npx cap add ios || true
          npx cap sync ios
      
      - name: Configure app icons
        script: |
          # Create AppIcon.appiconset if it doesn't exist
          ICON_DIR="ios/App/App/Assets.xcassets/AppIcon.appiconset"
          mkdir -p "$ICON_DIR"
          
          # Copy and resize icons using sips (built into macOS)
          SOURCE_ICON="public/icons/luna-app-icon-1024.png"
          
          # Generate all required iOS icon sizes
          sips -z 20 20 "$SOURCE_ICON" --out "$ICON_DIR/Icon-20.png"
          sips -z 40 40 "$SOURCE_ICON" --out "$ICON_DIR/Icon-20@2x.png"
          sips -z 60 60 "$SOURCE_ICON" --out "$ICON_DIR/Icon-20@3x.png"
          sips -z 29 29 "$SOURCE_ICON" --out "$ICON_DIR/Icon-29.png"
          sips -z 58 58 "$SOURCE_ICON" --out "$ICON_DIR/Icon-29@2x.png"
          sips -z 87 87 "$SOURCE_ICON" --out "$ICON_DIR/Icon-29@3x.png"
          sips -z 40 40 "$SOURCE_ICON" --out "$ICON_DIR/Icon-40.png"
          sips -z 80 80 "$SOURCE_ICON" --out "$ICON_DIR/Icon-40@2x.png"
          sips -z 120 120 "$SOURCE_ICON" --out "$ICON_DIR/Icon-40@3x.png"
          sips -z 120 120 "$SOURCE_ICON" --out "$ICON_DIR/Icon-60@2x.png"
          sips -z 180 180 "$SOURCE_ICON" --out "$ICON_DIR/Icon-60@3x.png"
          sips -z 76 76 "$SOURCE_ICON" --out "$ICON_DIR/Icon-76.png"
          sips -z 152 152 "$SOURCE_ICON" --out "$ICON_DIR/Icon-76@2x.png"
          sips -z 167 167 "$SOURCE_ICON" --out "$ICON_DIR/Icon-83.5@2x.png"
          sips -z 1024 1024 "$SOURCE_ICON" --out "$ICON_DIR/Icon-1024.png"
          
          # Create Contents.json for the icon set
          cat > "$ICON_DIR/Contents.json" << 'EOF'
          {
            "images": [
              {"size": "20x20", "idiom": "iphone", "filename": "Icon-20@2x.png", "scale": "2x"},
              {"size": "20x20", "idiom": "iphone", "filename": "Icon-20@3x.png", "scale": "3x"},
              {"size": "29x29", "idiom": "iphone", "filename": "Icon-29@2x.png", "scale": "2x"},
              {"size": "29x29", "idiom": "iphone", "filename": "Icon-29@3x.png", "scale": "3x"},
              {"size": "40x40", "idiom": "iphone", "filename": "Icon-40@2x.png", "scale": "2x"},
              {"size": "40x40", "idiom": "iphone", "filename": "Icon-40@3x.png", "scale": "3x"},
              {"size": "60x60", "idiom": "iphone", "filename": "Icon-60@2x.png", "scale": "2x"},
              {"size": "60x60", "idiom": "iphone", "filename": "Icon-60@3x.png", "scale": "3x"},
              {"size": "20x20", "idiom": "ipad", "filename": "Icon-20.png", "scale": "1x"},
              {"size": "20x20", "idiom": "ipad", "filename": "Icon-20@2x.png", "scale": "2x"},
              {"size": "29x29", "idiom": "ipad", "filename": "Icon-29.png", "scale": "1x"},
              {"size": "29x29", "idiom": "ipad", "filename": "Icon-29@2x.png", "scale": "2x"},
              {"size": "40x40", "idiom": "ipad", "filename": "Icon-40.png", "scale": "1x"},
              {"size": "40x40", "idiom": "ipad", "filename": "Icon-40@2x.png", "scale": "2x"},
              {"size": "76x76", "idiom": "ipad", "filename": "Icon-76.png", "scale": "1x"},
              {"size": "76x76", "idiom": "ipad", "filename": "Icon-76@2x.png", "scale": "2x"},
              {"size": "83.5x83.5", "idiom": "ipad", "filename": "Icon-83.5@2x.png", "scale": "2x"},
              {"size": "1024x1024", "idiom": "ios-marketing", "filename": "Icon-1024.png", "scale": "1x"}
            ],
            "info": {"version": 1, "author": "xcode"}
          }
          EOF
          npx cap sync ios
      
      - name: Set build number
        script: |
          # Use Codemagic build number for auto-incrementing
          cd ios/App
          agvtool new-version -all $BUILD_NUMBER
          echo "Set build number to $BUILD_NUMBER"
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          if [ -f "Podfile" ]; then
            pod install --repo-update
          else
            echo "No Podfile found - Capacitor may be using SPM"
          fi
      
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
